export const actionTypes = {
  SET_QUESTIONS: "SET_QUESTIONS",
  SET_LOADING_QUESTIONS: "SET_LOADING_QUESTIONS",
  DELETE_QUESTION: "DELETE_QUESTION",
  ANSWER_QUESTION: "ANSWER_QUESTION",
  FILTER_BY_SEARCH: "FILTER_BY_SEARCH",
};
