export const actionTypes = {
  SET_LOADING_USER: "SET_LOADING_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_OUT: "LOGIN_OUT",
  RESET_ERROR_FIELDS: "RESET_ERROR_FIELDS",
};
