export const actionTypes = {
  SET_NEWS: "SET_NEWS",
  SET_LOADING_NEWS: "SET_LOADING_NEWS",
  CHANGE_FILTER_QUERY_NEWS: "CHANGE_FILTER_QUERY_NEWS",
  DELETE_NEWS: "DELETE_NEWS",
  CHANGE_NEWS: "CHANGE_NEWS",
  ADD_NEWS: "ADD_NEWS",
};
